apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    admission.datadoghq.com/enabled: “true”
    app: browser-campaign
    code: SGS01013
    env: dev2
    part-of: browser-campaign
    tags.datadoghq.com/env: dev2
    tags.datadoghq.com/service: browser-campaign
    tags.datadoghq.com/version: campaign-1.0.9-idc___c3bae892
  name: browser-campaign
  namespace: sgs-dev2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: browser-campaign
      env: dev2
  strategy:
    rollingUpdate:
      maxSurge: 35%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        admission.datadoghq.com/js-lib.version: v5.19.0
      labels:
        admission.datadoghq.com/enabled: “true”
        app: browser-campaign
        code: SGS01013
        env: dev2
        part-of: browser-campaign
    spec:
      containers:
      - env:
        - name: ENABLE_SIPLOG
          value: “true”
        - name: APP_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels[‘app’]
        - name: ENV
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels[‘env’]
        - name: SERVER
          value: dev2
        - name: DD_PROFILING_ENABLED
          value: “true”
        - name: DD_LOGS_INJECTION
          value: “true”
        image: registry.idc-sginfra.net/stove-platform/browser-campaign:campaign-1.0.9-idc___c3bae892
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3000
          timeoutSeconds: 1
        name: browser-campaign
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3000
          timeoutSeconds: 1
        startupProbe:
          failureThreshold: 20
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3000
          timeoutSeconds: 1 