# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache 2.0 License.
#
# This product includes software developed at Datadog (https://www.datadoghq.com/)
# Copyright 2023 Datadog, Inc.
targetSystem: "linux"
clusterAgent:
  replicas: 2
  createPodDisruptionBudget: true
  admissionController:
    enabled: true
    mutateUnlabelled: true
datadog:
  apiKeyExistingSecret: datadog-secret
  apm:
    instrumentation:
      enabled: true
      libVersions:
        java: v1.36.0      
    portEnabled: true
  tags:
    - "team:infra"
    - "env:prod"
    - "provider:aws"
  networkMonitoring:
    enabled: true
  processAgent:
    enabled: true
    processCollection: true


